ruby '>= 3'

group :development do
  source 'https://www.rubygems.org' do
    gem 'rake'
    gem 'rspec'
    gem 'rubocop'
    gem 'rubocop-performance'
    gem 'rubocop-rake'
    gem 'rubocop-rspec'
  end

  source 'https://www.jubigems.org' do
    gem 'rakegem'
  end
end

# Specify your gem's dependencies in %gem%.gemspec
gemspec
